behaviors:
    AmanAaditya:
        trainer_type: ppo
        hyperparameters:
            batch_size: 128
            buffer_size: 2048
            learning_rate: 0.0003
            beta: 0.01
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 8
            learning_rate_schedule: constant
        network_settings:
            normalize: false
            hidden_units: 256
            num_layers: 2
            vis_encode_type: simple
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1
            curiosity:
                strength: 0.025
                gamma: 0.99
                learning_rate: 0.0003      
            gail:
                strength: 0.7
                demo_path: /home/tonystark/MTP_AadityaAman/UNity_Env/MTP_Env/Assets/Demonstrations/AmanAaditya_1.demo
        keep_checkpoints: 5
        max_steps: 5000000
        time_horizon: 128
        summary_freq: 5000
        threaded: true

